const Admin = [
  "seichenbaum@achievebh.org",
  "Areiner@achievebbh.org",
  "jfrohlich@achievebh.org",
  "chager@achievebh.org",
  "nkutin@achievebh.org",
  "ozharnest@achievebh.org",
  "mgalla@achievebh.org",
  "ygenack@achievebh.org",
  "jweiss@achievebh.org",
  "bmayer@achievebh.org              ",
  "rashkenas@achievebh.org              ",
  "yedidagenack@achievebh.org              ",
  "tschiller@achievebh.org              ",
  "ylichter@achievebh.org              ",
  "smarkowitz@achievebh.org              ",
  "ynissenfeld@achievebh.org              ",
  "mgrunfeld@achievebh.org              ",
  "ychesner@achievebh.org              ",
  "yhalle@achievebh.org              ",
  "ahirschfeld@achievebh.org              ",
  "mbineth@achievebh.org              ",
  "mplattie@achievebh.org              ",
  "ghoffnung@achievebh.org",
  "ylunger@achievebh.org",
  "jbaumhaft@achievebh.org",
];
export default Admin;
